#  NumPy

- NumPy is used for working with arrays.
- Short for 'Numerical Python'
- It also has functions for working in domain of linear algebra, fourier transform, and matrices
- Has support for N dimensional array

### Why NumPy ?
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate     them very efficiently.
- This behavior is called locality of reference in computer science.

In [3]:
import numpy as np

# 1.1 Create

In [4]:
data = np.random.rand(2,3,4)
zeros = np.zeros((2,2,2))
full = np.full((2,2,2),7)
ones = np.ones((2,2,2))

In [5]:
data


array([[[0.46566796, 0.59216683, 0.72461728, 0.18563465],
        [0.36129672, 0.82996179, 0.94007407, 0.55884191],
        [0.01541504, 0.14457982, 0.09359914, 0.01609773]],

       [[0.46996231, 0.80541989, 0.83162797, 0.04402529],
        [0.94612744, 0.08486987, 0.0436827 , 0.96924657],
        [0.11836229, 0.73880474, 0.66724862, 0.30860654]]])

In [6]:
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [7]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [8]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

## 1.2 Read

In [9]:
# key attributes of nupy arrays
shape = data.shape
size = data.size   # number of elements
types = data.dtype

In [10]:
shape


(2, 3, 4)

In [11]:
size

24

In [12]:
types

dtype('float64')

## 1.3 Slicing

In [13]:
data

array([[[0.46566796, 0.59216683, 0.72461728, 0.18563465],
        [0.36129672, 0.82996179, 0.94007407, 0.55884191],
        [0.01541504, 0.14457982, 0.09359914, 0.01609773]],

       [[0.46996231, 0.80541989, 0.83162797, 0.04402529],
        [0.94612744, 0.08486987, 0.0436827 , 0.96924657],
        [0.11836229, 0.73880474, 0.66724862, 0.30860654]]])

In [14]:
arr = data[0]
arr

array([[0.46566796, 0.59216683, 0.72461728, 0.18563465],
       [0.36129672, 0.82996179, 0.94007407, 0.55884191],
       [0.01541504, 0.14457982, 0.09359914, 0.01609773]])

In [15]:
s1 = data[0][1][1]
s1

0.8299617855253929

In [16]:
s2 = data[0][1:]
s2

array([[0.36129672, 0.82996179, 0.94007407, 0.55884191],
       [0.01541504, 0.14457982, 0.09359914, 0.01609773]])

## 1.4 Update


In [17]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)


In [18]:
list1


array([0.30733011, 0.43611038, 0.23834356, 0.39829041, 0.44724184,
       0.96100418, 0.05282784, 0.87471913, 0.9513772 , 0.82940336])

In [19]:
list2

array([0.08008485, 0.34010184, 0.70487926, 0.12016962, 0.70515393,
       0.86038828, 0.34885457, 0.55534388, 0.37086477, 0.86334336])

In [20]:
#basic math functions
add = np.add(list1,list2)
sub = np.subtract(list1,list2)
div = np.divide(list1,list2)
mul = np.multiply(list1,list2)
dot = np.dot(list1,list2)


In [21]:
add

array([0.38741496, 0.77621222, 0.94322282, 0.51846003, 1.15239576,
       1.82139247, 0.40168241, 1.43006301, 1.32224197, 1.69274672])

In [22]:
sub

array([ 0.22724526,  0.09600854, -0.46653571,  0.27812079, -0.25791209,
        0.1006159 , -0.29602673,  0.31937525,  0.58051242, -0.03393999])

In [23]:
div

array([3.83755629, 1.2822935 , 0.33813388, 3.3144018 , 0.6342471 ,
       1.11694244, 0.15143227, 1.57509456, 2.56529404, 0.96068772])

In [24]:
mul

array([0.02461248, 0.14832194, 0.16800343, 0.04786241, 0.31537434,
       0.82683674, 0.01842923, 0.48576992, 0.35283229, 0.71605988])

In [25]:
dot

3.1041026621817487

In [26]:
# stat functions---(sap lemm)
sqrt = np.sqrt(list1)
ab = np.abs(-3)
power = np.power([2,2,2],[2,1,0])  # array1 raised to exponents in array2
log = np.log(25)
exp = np.exp([2,3])  #returns an array with exponential of all elements of input array.
mins = np.min(list1)
maxs = np.max(list2)

In [27]:
power

array([4, 2, 1])

In [28]:
exp

array([ 7.3890561 , 20.08553692])

In [29]:
mins

0.052827840165709405

In [30]:
maxs


0.8633433551030486

## 1.5 Reshaping

In [31]:
print(data.shape)

(2, 3, 4)


In [32]:
data = data.reshape(2,2,-1)   #allowed to have one unknown dimensio
data.shape

(2, 2, 6)

In [57]:
#append()

list3 = np.full([2,3],9)
list3 = np.append(list3,[66])
list3


array([ 9,  9,  9,  9,  9,  9, 66])

In [61]:
# insert()

list3 = np.insert(list3,4,88)
list3


array([ 9,  9,  9,  9, 88,  9,  9, 66,  1])