# 1. NumPy

- NumPy is used for working with arrays.
- Short for 'Numerical Python'
- It also has functions for working in domain of linear algebra, fourier transform, and matrices
- Has support for N dimensional array

### Why NumPy ?
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate     them very efficiently.
- This behavior is called locality of reference in computer science.

In [1]:
import numpy as np

# 1.1 Create

In [4]:
data = np.random.rand(2,3,4)
zeros = np.zeros((2,2,2))
full = np.full((2,2,2),7)
ones = np.ones((2,2,2))

In [6]:
data


array([[[0.20748134, 0.48032038, 0.8979464 , 0.20025759],
        [0.76453676, 0.90182434, 0.23601356, 0.52829327],
        [0.20138967, 0.12108069, 0.89770738, 0.88880349]],

       [[0.54128486, 0.77817567, 0.03874227, 0.7507657 ],
        [0.92901983, 0.32199217, 0.0882579 , 0.97878853],
        [0.00298111, 0.13953065, 0.30716295, 0.56337187]]])

In [7]:
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [8]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [9]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

## 1.2 Read

In [10]:
# key attributes of nupy arrays
shape = data.shape
size = data.size   # number of elements
types = data.dtype

In [16]:
shape


(2, 3, 4)

In [12]:
size

24

In [14]:
types

dtype('float64')

## 1.3 Slicing

In [20]:
data

array([[[0.20748134, 0.48032038, 0.8979464 , 0.20025759],
        [0.76453676, 0.90182434, 0.23601356, 0.52829327],
        [0.20138967, 0.12108069, 0.89770738, 0.88880349]],

       [[0.54128486, 0.77817567, 0.03874227, 0.7507657 ],
        [0.92901983, 0.32199217, 0.0882579 , 0.97878853],
        [0.00298111, 0.13953065, 0.30716295, 0.56337187]]])

In [21]:
arr = data[0]
arr

array([[0.20748134, 0.48032038, 0.8979464 , 0.20025759],
       [0.76453676, 0.90182434, 0.23601356, 0.52829327],
       [0.20138967, 0.12108069, 0.89770738, 0.88880349]])

In [22]:
s1 = data[0][1][1]
s1

0.901824335272361

In [29]:
s2 = data[0][1:]
s2

array([[0.76453676, 0.90182434, 0.23601356, 0.52829327],
       [0.20138967, 0.12108069, 0.89770738, 0.88880349]])

## 1.4 Update


In [32]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)


In [33]:
list1


array([0.46896257, 0.06164376, 0.01191004, 0.10968548, 0.31053523,
       0.07310445, 0.08209714, 0.41755692, 0.62001898, 0.0087792 ])

In [34]:
list2

array([0.72351165, 0.42516963, 0.52010981, 0.40550025, 0.25943816,
       0.6818814 , 0.18848839, 0.90062156, 0.43111923, 0.72737926])