# 1. NumPy

- NumPy is used for working with arrays.
- Short for 'Numerical Python'
- It also has functions for working in domain of linear algebra, fourier transform, and matrices
- Has support for N dimensional array

### Why NumPy ?
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate     them very efficiently.
- This behavior is called locality of reference in computer science.

In [1]:
import numpy as np

# 1.1 Create

In [4]:
data = np.random.rand(2,3,4)
zeros = np.zeros((2,2,2))
full = np.full((2,2,2),7)
ones = np.ones((2,2,2))

In [6]:
data


array([[[0.20748134, 0.48032038, 0.8979464 , 0.20025759],
        [0.76453676, 0.90182434, 0.23601356, 0.52829327],
        [0.20138967, 0.12108069, 0.89770738, 0.88880349]],

       [[0.54128486, 0.77817567, 0.03874227, 0.7507657 ],
        [0.92901983, 0.32199217, 0.0882579 , 0.97878853],
        [0.00298111, 0.13953065, 0.30716295, 0.56337187]]])

In [7]:
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [8]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [9]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

## 1.2 Read

In [10]:
# key attributes of nupy arrays
shape = data.shape
size = data.size   # number of elements
types = data.dtype

In [16]:
shape


(2, 3, 4)

In [12]:
size

24

In [14]:
types

dtype('float64')

## 1.3 Slicing

In [20]:
data

array([[[0.20748134, 0.48032038, 0.8979464 , 0.20025759],
        [0.76453676, 0.90182434, 0.23601356, 0.52829327],
        [0.20138967, 0.12108069, 0.89770738, 0.88880349]],

       [[0.54128486, 0.77817567, 0.03874227, 0.7507657 ],
        [0.92901983, 0.32199217, 0.0882579 , 0.97878853],
        [0.00298111, 0.13953065, 0.30716295, 0.56337187]]])

In [21]:
arr = data[0]
arr

array([[0.20748134, 0.48032038, 0.8979464 , 0.20025759],
       [0.76453676, 0.90182434, 0.23601356, 0.52829327],
       [0.20138967, 0.12108069, 0.89770738, 0.88880349]])

In [22]:
s1 = data[0][1][1]
s1

0.901824335272361

In [29]:
s2 = data[0][1:]
s2

array([[0.76453676, 0.90182434, 0.23601356, 0.52829327],
       [0.20138967, 0.12108069, 0.89770738, 0.88880349]])

## 1.4 Update


In [32]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)


In [33]:
list1


array([0.46896257, 0.06164376, 0.01191004, 0.10968548, 0.31053523,
       0.07310445, 0.08209714, 0.41755692, 0.62001898, 0.0087792 ])

In [37]:
list2

array([0.72351165, 0.42516963, 0.52010981, 0.40550025, 0.25943816,
       0.6818814 , 0.18848839, 0.90062156, 0.43111923, 0.72737926])

In [39]:
#basic math functions
add = np.add(list1,list2)
sub = np.subtract(list1,list2)
div = np.divide(list1,list2)
mul = np.multiply(list1,list2)
dot = np.dot(list1,list2)


In [40]:
add

array([1.19247421, 0.48681339, 0.53201986, 0.51518573, 0.56997339,
       0.75498585, 0.27058553, 1.31817848, 1.05113821, 0.73615846])

In [41]:
sub

array([-0.25454908, -0.36352586, -0.50819977, -0.29581477,  0.05109707,
       -0.60877694, -0.10639124, -0.48306465,  0.18889975, -0.71860006])

In [42]:
div

array([0.64817556, 0.14498628, 0.02289909, 0.27049423, 1.1969528 ,
       0.10720992, 0.43555545, 0.46363193, 1.43816126, 0.01206963])

In [43]:
mul

array([0.33929988, 0.02620906, 0.00619453, 0.04447749, 0.08056469,
       0.04984857, 0.01547436, 0.37606076, 0.26730211, 0.00638581])

In [44]:
dot

1.211817243884774

In [52]:
# stat functions---(sap lemm)
sqrt = np.sqrt(list1)
ab = np.abs(-3)
power = np.power([2,2,2],[2,1,0])  # array1 raised to exponents in array2
log = np.log(25)
exp = np.exp([2,3])

In [50]:
power

array([4, 2, 1])

In [53]:
exp

array([ 7.3890561 , 20.08553692])